
versiion: 2
jobs:
    build:
        working_directorry: ~
        docker:
            - image: circleci/python
        steps:
            - checkout
            - run:
                command: |
                    sudo pip3 install pep8
                    pep8 .
